name: Sentinel Gate
description: Validates that the Sentinel code review covers the current PR head SHA
inputs:
  mode:
    description: 'write | check'
    required: true
  sha:
    description: 'The SHA being reviewed (write mode) or current head (check mode)'
    required: true
  verdict:
    description: 'pass or fail (write mode only)'
    required: false
    default: 'pass'
  findings:
    description: 'JSON array of findings (write mode only)'
    required: false
    default: '[]'
runs:
  using: composite
  steps:
    - name: Write review manifest
      if: inputs.mode == 'write'
      shell: bash
      run: |
        mkdir -p .sentinel
        echo '{
          "sha": "${{ inputs.sha }}",
          "verdict": "${{ inputs.verdict }}",
          "findings": ${{ inputs.findings }},
          "reviewed_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
        }' > .sentinel/review-manifest.json
        echo "Review manifest written for SHA ${{ inputs.sha }}"

    - name: Upload review manifest
      if: inputs.mode == 'write'
      uses: actions/upload-artifact@v4
      with:
        name: sentinel-review-${{ inputs.sha }}
        path: .sentinel/review-manifest.json
        retention-days: 7

    - name: Check SHA discipline
      if: inputs.mode == 'check'
      shell: bash
      run: |
        # Find the latest sentinel review artifact for this PR
        ARTIFACT_NAME="sentinel-review-${{ inputs.sha }}"

        # Download the artifact
        gh api repos/${{ github.repository }}/actions/artifacts \
          --jq "[.artifacts[] | select(.name == \"$ARTIFACT_NAME\")] | .[0].id" > /tmp/artifact_id.txt

        ARTIFACT_ID=$(cat /tmp/artifact_id.txt)

        if [[ -z "$ARTIFACT_ID" || "$ARTIFACT_ID" == "null" ]]; then
          echo "❌ No Sentinel review found for SHA ${{ inputs.sha }}"
          echo "Expected artifact: $ARTIFACT_NAME"
          exit 1
        fi

        # Download and extract the artifact content
        mkdir -p /tmp/sentinel-artifact
        gh api repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip > /tmp/sentinel-artifact.zip
        unzip -o /tmp/sentinel-artifact.zip -d /tmp/sentinel-artifact

        # Read the manifest
        MANIFEST=/tmp/sentinel-artifact/review-manifest.json
        if [[ ! -f "$MANIFEST" ]]; then
          echo "❌ review-manifest.json not found in artifact"
          exit 1
        fi

        REVIEW_SHA=$(jq -r '.sha' "$MANIFEST")
        VERDICT=$(jq -r '.verdict // "unknown"' "$MANIFEST")
        CURRENT_SHA="${{ inputs.sha }}"

        echo "Review SHA:  $REVIEW_SHA"
        echo "Current SHA: $CURRENT_SHA"
        echo "Verdict:     $VERDICT"

        if [[ "$REVIEW_SHA" != "$CURRENT_SHA" ]]; then
          echo "❌ SHA mismatch — review is stale. Sentinel must re-review current head."
          exit 1
        fi

        if [[ "$VERDICT" == "fail" ]]; then
          echo "❌ Sentinel review verdict: FAIL"
          exit 1
        fi

        echo "✅ SHA discipline check passed"
      env:
        GH_TOKEN: ${{ github.token }}
