name: Sentinel Gate
description: Validates that the Sentinel code review covers the current PR head SHA
inputs:
  mode:
    description: 'write | check'
    required: true
  sha:
    description: 'The SHA being reviewed (write mode) or current head (check mode)'
    required: true
  verdict:
    description: 'pass or fail (write mode only)'
    required: false
    default: 'pass'
  findings:
    description: 'JSON array of findings (write mode only)'
    required: false
    default: '[]'
runs:
  using: composite
  steps:
    - name: Write review manifest
      if: inputs.mode == 'write'
      shell: bash
      run: |
        mkdir -p .sentinel
        echo '{
          "sha": "${{ inputs.sha }}",
          "verdict": "${{ inputs.verdict }}",
          "findings": ${{ inputs.findings }},
          "reviewed_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"
        }' > .sentinel/review-manifest.json
        echo "Review manifest written for SHA ${{ inputs.sha }}"

    - name: Upload review manifest
      if: inputs.mode == 'write'
      uses: actions/upload-artifact@v4
      with:
        name: sentinel-review-${{ inputs.sha }}
        path: .sentinel/review-manifest.json
        retention-days: 7

    - name: Check SHA discipline
      if: inputs.mode == 'check'
      shell: bash
      run: |
        # Download latest sentinel review artifact
        ARTIFACTS=$(gh api repos/${{ github.repository }}/actions/artifacts \
          --jq '[.artifacts[] | select(.name | startswith("sentinel-review-"))] | sort_by(.created_at) | reverse | .[0]')

        if [[ -z "$ARTIFACTS" || "$ARTIFACTS" == "null" ]]; then
          echo "❌ No Sentinel review found for this PR"
          exit 1
        fi

        REVIEW_SHA=$(echo "$ARTIFACTS" | jq -r '.name' | sed 's/sentinel-review-//')
        CURRENT_SHA="${{ inputs.sha }}"

        echo "Review SHA:  $REVIEW_SHA"
        echo "Current SHA: $CURRENT_SHA"

        if [[ "$REVIEW_SHA" != "$CURRENT_SHA" ]]; then
          echo "❌ SHA mismatch — review is stale. Sentinel must re-review current head."
          exit 1
        fi

        # Check verdict
        VERDICT=$(echo "$ARTIFACTS" | jq -r '.verdict // "unknown"')
        if [[ "$VERDICT" == "fail" ]]; then
          echo "❌ Sentinel review verdict: FAIL"
          exit 1
        fi

        echo "✅ SHA discipline check passed — review matches current head"
      env:
        GH_TOKEN: ${{ github.token }}
