/**
 * Test Fixtures
 * Sprint 3.4: Shared test utilities
 * 
 * Factory functions for creating mock task data
 */

// Type-only import for task ID - will be generated by Convex
type Id<T extends string> = string & { __tableName: T }

export type TaskStatus =
  | 'planning'
  | 'ready'
  | 'in_progress'
  | 'in_review'
  | 'done'
  | 'blocked'
  | 'cancelled'
  | 'pending' // legacy
  | 'active' // legacy

export type TaskPriority = 'low' | 'normal' | 'high' | 'urgent'

export interface MockTask {
  _id: Id<'tasks'>
  _creationTime: number
  title: string
  description?: string
  assignedAgent?: string
  createdBy: string
  status: TaskStatus
  priority: TaskPriority
  createdAt: number
  startedAt?: number
  completedAt?: number
  dueAt?: number
  parentTask?: Id<'tasks'>
  dependsOn?: Id<'tasks'>[]
  project?: string
  notes?: string
  tags?: string[]
  result?: string
  blockedReason?: string
  leaseOwner?: string
  leaseExpiresAt?: number
  handoffCount?: number
  version?: number
  handoffPayload?: {
    contextSummary: string
    filesChanged: string[]
    testsPassed: boolean
    remainingRisk: string
  }
  attemptCount?: number
  lastHeartbeatAt?: number
}

/**
 * Creates a mock task with default values
 * 
 * @param overrides - Partial task object to override defaults
 * @returns Complete mock task object
 * 
 * @example
 * const task = createMockTask({
 *   title: 'My Task',
 *   status: 'in_progress',
 *   priority: 'high',
 * })
 */
export function createMockTask(overrides: Partial<MockTask> = {}): MockTask {
  const now = Date.now()
  const taskId = (overrides._id ?? `j57${Math.random().toString(36).slice(2, 15)}`) as Id<'tasks'>
  
  return {
    _id: taskId,
    _creationTime: now,
    title: 'Mock Task',
    description: undefined,
    assignedAgent: 'unassigned',
    createdBy: 'main',
    status: 'planning',
    priority: 'normal',
    createdAt: now,
    startedAt: undefined,
    completedAt: undefined,
    dueAt: undefined,
    parentTask: undefined,
    dependsOn: undefined,
    project: undefined,
    notes: undefined,
    tags: undefined,
    result: undefined,
    blockedReason: undefined,
    leaseOwner: undefined,
    leaseExpiresAt: undefined,
    handoffCount: undefined,
    version: undefined,
    handoffPayload: undefined,
    attemptCount: undefined,
    lastHeartbeatAt: undefined,
    ...overrides,
  }
}

/**
 * Creates multiple mock tasks with different statuses
 * 
 * @param count - Number of tasks to create per status
 * @returns Array of mock tasks
 */
export function createMockTasksByStatus(count: number = 1): MockTask[] {
  const statuses: TaskStatus[] = [
    'planning',
    'ready',
    'in_progress',
    'in_review',
    'done',
    'blocked',
  ]
  
  const tasks: MockTask[] = []
  
  statuses.forEach((status) => {
    for (let i = 0; i < count; i++) {
      tasks.push(
        createMockTask({
          title: `${status.replace('_', ' ')} Task ${i + 1}`,
          status,
          priority: i % 2 === 0 ? 'normal' : 'high',
          assignedAgent: ['forge', 'sentinel', 'oracle', 'friday'][i % 4],
          project: i % 2 === 0 ? 'agent-dashboard' : 'options-trader',
        })
      )
    }
  })
  
  return tasks
}

/**
 * Creates a mock task with handoff payload
 * 
 * @param overrides - Partial task object to override defaults
 * @returns Mock task with handoff payload
 */
export function createMockHandoffTask(overrides: Partial<MockTask> = {}): MockTask {
  return createMockTask({
    status: 'in_review',
    assignedAgent: 'sentinel',
    handoffCount: 1,
    handoffPayload: {
      contextSummary: 'PR #123 created with feature implementation',
      filesChanged: ['src/component.tsx', 'src/test.ts'],
      testsPassed: true,
      remainingRisk: 'Low - all tests passing',
    },
    leaseOwner: 'forge-j57abc123',
    leaseExpiresAt: Date.now() + 3600000,
    ...overrides,
  })
}

/**
 * Creates a mock blocked task
 * 
 * @param overrides - Partial task object to override defaults
 * @returns Mock blocked task
 */
export function createMockBlockedTask(overrides: Partial<MockTask> = {}): MockTask {
  return createMockTask({
    status: 'blocked',
    priority: 'urgent',
    blockedReason: 'Waiting for external dependency',
    dependsOn: ['j57dependency123' as Id<'tasks'>],
    ...overrides,
  })
}

/**
 * Creates a mock task with dependencies
 * 
 * @param dependencyCount - Number of dependencies to create
 * @param overrides - Partial task object to override defaults
 * @returns Mock task with dependencies
 */
export function createMockTaskWithDependencies(
  dependencyCount: number = 2,
  overrides: Partial<MockTask> = {}
): MockTask {
  const dependencies = Array.from({ length: dependencyCount }, (_, i) =>
    `j57dep${i}${Math.random().toString(36).slice(2, 8)}` as Id<'tasks'>
  )
  
  return createMockTask({
    dependsOn: dependencies,
    ...overrides,
  })
}

/**
 * Groups mock tasks by status for getByStatus query
 * 
 * @param tasks - Array of mock tasks
 * @returns Tasks grouped by status
 */
export function groupTasksByStatus(tasks: MockTask[]): Record<string, MockTask[]> {
  const grouped: Record<string, MockTask[]> = {
    planning: [],
    ready: [],
    in_progress: [],
    in_review: [],
    done: [],
    blocked: [],
  }
  
  for (const task of tasks) {
    const status = task.status || 'planning'
    if (grouped[status]) {
      grouped[status].push(task)
    }
  }
  
  return grouped
}
