#!/usr/bin/env bash
# Generate stub files for CI when Convex backend is not available

set -e

echo "Generating stub files for CI..."

# Create directories
mkdir -p convex/_generated
mkdir -p src

# Generate convex/_generated/server.ts stub
cat > convex/_generated/server.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh

type QueryChain = {
  withIndex: (
    index: string,
    indexFn?: (q: { eq: (field: string, value: any) => any }) => any
  ) => QueryChain;
  first: () => Promise<any>;
  order: (order: string) => {
    take: (n: number) => Promise<any[]>;
    collect: () => Promise<any[]>;
  };
}

/** Minimal Auth interface matching convex/server Auth (getUserIdentity). */
export interface Auth {
  getUserIdentity(): Promise<{ tokenIdentifier: string; subject: string; issuer: string; [key: string]: any } | null>;
}

export interface QueryCtx {
  db: {
    query: (table: string) => QueryChain;
    get: (id: any) => Promise<any>;
  };
  runQuery: (query: any, args: any) => Promise<any>;
  // [security] auth field required for getUserIdentity guards (j57bds0a8vv8qk349dqsnfw65h81d99x)
  auth: Auth;
}

export interface MutationCtx extends QueryCtx {
  db: {
    query: (table: string) => QueryChain;
    insert: (table: string, doc: any) => Promise<any>;
    patch: (id: any, fields: any) => Promise<void>;
    delete: (id: any) => Promise<void>;
    get: (id: any) => Promise<any>;
  };
  runMutation: (mutation: any, args: any) => Promise<any>;
  // auth is inherited from QueryCtx
}

export const query = <Args = any, Output = any>(config: {
  args?: Args;
  handler: (ctx: QueryCtx, args?: Args) => Promise<Output>;
}) => config;

export const mutation = <Args = any, Output = any>(config: {
  args?: Args;
  handler: (ctx: MutationCtx, args?: Args) => Promise<Output>;
}) => config;

export const action = (fn: any) => fn;
export const internalQuery = (fn: any) => fn;
export const internalMutation = (fn: any) => fn;
export const internalAction = (fn: any) => fn;
EOF


# Generate convex/_generated/dataModel.ts stub
cat > convex/_generated/dataModel.ts << 'DATAMODELSTUB'
// Stub file for CI - generated by scripts/generate-stubs.sh

// Generic document type — returns any so tests can cast freely
export type Doc<_TableName extends string> = any;
// Generic ID type — a branded string
export type Id<_TableName extends string> = string & { __tableName?: _TableName };
DATAMODELSTUB

# Always generate convex/_generated/api.ts stub.
# When server.ts and dataModel.ts stubs are generated, the real api.d.ts
# (which uses `typeof tasks` + Convex's FilterApi) no longer resolves correctly
# because the stub server types don't produce FunctionReference shapes.
# The api.ts stub overrides api.d.ts and provides a consistent surface for both
# CI (no backend) and local pre-push checks.
cat > convex/_generated/api.ts << 'APISTUB'
// Stub file for CI - generated by scripts/generate-stubs.sh
// Uses makeFunctionReference so useMutation/useQuery receive valid Convex function references
import { makeFunctionReference } from 'convex/server';

export const api = {
  tasks: {
    list:                     makeFunctionReference<'query'>('tasks:list'),
    getByStatus:              makeFunctionReference<'query'>('tasks:getByStatus'),
    getAgentPresence:         makeFunctionReference<'query'>('tasks:getAgentPresence'),
    getWorkload:              makeFunctionReference<'query'>('tasks:getWorkload'),
    listFiltered:             makeFunctionReference<'query'>('tasks:listFiltered'),
    getById:                  makeFunctionReference<'query'>('tasks:getById'),
    searchTasks:              makeFunctionReference<'query'>('tasks:searchTasks'),
    getMetrics:               makeFunctionReference<'query'>('tasks:getMetrics'),
    getBoard:                 makeFunctionReference<'query'>('tasks:getBoard'),
    getWorkloadByAgentStatus: makeFunctionReference<'query'>('tasks:getWorkloadByAgentStatus'),
    listTasks:                makeFunctionReference<'query'>('tasks:listTasks'),
    getTask:                  makeFunctionReference<'query'>('tasks:getTask'),
    create:                   makeFunctionReference<'mutation'>('tasks:create'),
    createTask:               makeFunctionReference<'mutation'>('tasks:createTask'),
    update:                   makeFunctionReference<'mutation'>('tasks:update'),
    updateTask:               makeFunctionReference<'mutation'>('tasks:updateTask'),
    claimTask:                makeFunctionReference<'mutation'>('tasks:claimTask'),
    heartbeat:                makeFunctionReference<'mutation'>('tasks:heartbeat'),
    completeTask:             makeFunctionReference<'mutation'>('tasks:completeTask'),
    deleteTask:               makeFunctionReference<'mutation'>('tasks:deleteTask'),
    startTask:                makeFunctionReference<'mutation'>('tasks:startTask'),
    submitForReview:          makeFunctionReference<'mutation'>('tasks:submitForReview'),
    submitForReviewAndAssign: makeFunctionReference<'mutation'>('tasks:submitForReviewAndAssign'),
    handoffTask:              makeFunctionReference<'mutation'>('tasks:handoffTask'),
    pushStatus:               makeFunctionReference<'mutation'>('tasks:pushStatus'),
    pushEvent:                makeFunctionReference<'mutation'>('tasks:pushEvent'),
  },
  activityLog: {
    getTaskActivity:   makeFunctionReference<'query'>('activityLog:getTaskActivity'),
    getRecentActivity: makeFunctionReference<'query'>('activityLog:getRecentActivity'),
    logActivity:       makeFunctionReference<'mutation'>('activityLog:logActivity'),
  },
  pushTokens: {
    getUserTokens:  makeFunctionReference<'query'>('pushTokens:getUserTokens'),
    getDeviceToken: makeFunctionReference<'query'>('pushTokens:getDeviceToken'),
    registerToken:  makeFunctionReference<'mutation'>('pushTokens:registerToken'),
    deleteToken:    makeFunctionReference<'mutation'>('pushTokens:deleteToken'),
    updateLastUsed: makeFunctionReference<'mutation'>('pushTokens:updateLastUsed'),
  },
  costTelemetry: {
    listByTask:           makeFunctionReference<'query'>('costTelemetry:listByTask'),
    listByRun:            makeFunctionReference<'query'>('costTelemetry:listByRun'),
    getAnalytics:         makeFunctionReference<'query'>('costTelemetry:getAnalytics'),
    getAnomalyPrimitives: makeFunctionReference<'query'>('costTelemetry:getAnomalyPrimitives'),
    record:               makeFunctionReference<'mutation'>('costTelemetry:record'),
  },
  userPreferences: {
    getUserPreferences: makeFunctionReference<'query'>('userPreferences:getUserPreferences'),
    setUserPreferences: makeFunctionReference<'mutation'>('userPreferences:setUserPreferences'),
  },
};

export const internal = {
  notifications: {
    notifyTaskDone: makeFunctionReference<'mutation'>('notifications:notifyTaskDone'),
  },
  tasks: {
    create:                   makeFunctionReference<'mutation'>('tasks:create'),
    update:                   makeFunctionReference<'mutation'>('tasks:update'),
    remove:                   makeFunctionReference<'mutation'>('tasks:remove'),
    backfillFriendlyTaskKeys: makeFunctionReference<'mutation'>('tasks:backfillFriendlyTaskKeys'),
  },
};
APISTUB

echo "✅ Stub files generated successfully"
