#!/usr/bin/env bash
# Generate stub files for CI when Convex backend is not available

set -e

echo "Generating stub files for CI..."

# Create directories
mkdir -p convex/_generated
mkdir -p src

# Generate convex/_generated/server.ts stub
cat > convex/_generated/server.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh

type QueryChain = {
  withIndex: (
    index: string,
    indexFn?: (q: { eq: (field: string, value: any) => any }) => any
  ) => QueryChain;
  first: () => Promise<any>;
  order: (order: string) => {
    take: (n: number) => Promise<any[]>;
    collect: () => Promise<any[]>;
  };
}

/** Minimal Auth interface matching convex/server Auth (getUserIdentity). */
export interface Auth {
  getUserIdentity(): Promise<{ tokenIdentifier: string; subject: string; issuer: string; [key: string]: any } | null>;
}

export interface QueryCtx {
  db: {
    query: (table: string) => QueryChain;
    get: (id: any) => Promise<any>;
  };
  runQuery: (query: any, args: any) => Promise<any>;
  // [security] auth field required for getUserIdentity guards (j57bds0a8vv8qk349dqsnfw65h81d99x)
  auth: Auth;
}

export interface MutationCtx extends QueryCtx {
  db: {
    query: (table: string) => QueryChain;
    insert: (table: string, doc: any) => Promise<any>;
    patch: (id: any, fields: any) => Promise<void>;
    delete: (id: any) => Promise<void>;
    get: (id: any) => Promise<any>;
  };
  runMutation: (mutation: any, args: any) => Promise<any>;
  // auth is inherited from QueryCtx
}

export const query = <Args = any, Output = any>(config: {
  args?: Args;
  handler: (ctx: QueryCtx, args?: Args) => Promise<Output>;
}) => config;

export const mutation = <Args = any, Output = any>(config: {
  args?: Args;
  handler: (ctx: MutationCtx, args?: Args) => Promise<Output>;
}) => config;

export const action = (fn: any) => fn;
export const internalQuery = (fn: any) => fn;
export const internalMutation = (fn: any) => fn;
export const internalAction = (fn: any) => fn;
EOF

# Always generate convex/_generated/api.ts stub.
# When server.ts and dataModel.ts stubs are generated, the real api.d.ts
# (which uses `typeof tasks` + Convex's FilterApi) no longer resolves correctly
# because the stub server types don't produce FunctionReference shapes.
# The api.ts stub overrides api.d.ts and provides a consistent surface for both
# CI (no backend) and local pre-push checks.
cat > convex/_generated/api.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh
export const api = {
  tasks: {
    list: {} as any,
    getByStatus: {} as any,
    getWorkload: {} as any,
    listFiltered: {} as any,
    getById: {} as any,
    create: {} as any,
    createTask: {} as any,
    update: {} as any,
    updateTask: {} as any,
    claimTask: {} as any,
    completeTask: {} as any,
    deleteTask: {} as any,
  },
  activityLog: {
    getRecentActivity: {} as any,
  },
  pushTokens: {
    getUserTokens: {} as any,
  },
};

export const internal = {
  notifications: {
    notifyTaskDone: {} as any,
  },
  tasks: {
    // [security] create/update/remove moved to internalMutation (j57bds0a8vv8qk349dqsnfw65h81d99x)
    create: {} as any,
    update: {} as any,
    remove: {} as any,
  },
};
EOF

# Generate convex/_generated/dataModel.ts stub
cat > convex/_generated/dataModel.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh

export type TableNames = string

export type Id<TableName extends TableNames = TableNames> = string & {
  __tableName: TableName
}

export type Doc<TableName extends TableNames = TableNames> = {
  _id: Id<TableName>
  _creationTime: number
} & Record<string, unknown>

// Keep the generic surface available for tests/types that import DataModel.
export type DataModel = Record<string, unknown>
EOF

# Generate src/routeTree.gen.ts stub unless explicitly disabled.
# E2E runs should keep the real generated route tree so routing works at runtime.
if [[ "${SKIP_ROUTE_TREE_STUB:-0}" != "1" ]]; then
  cat > src/routeTree.gen.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh
// This is a minimal stub to satisfy TypeScript during CI when TanStack Router
// codegen hasn't run. The actual routeTree will be generated by the router plugin.

export const routeTree: any = {
  __root__: {} as any,
}
EOF
fi

# Generate convex/_generated/dataModel.ts stub
cat > convex/_generated/dataModel.ts << 'EOF'
// Stub file for CI - generated by scripts/generate-stubs.sh

// Generic document type — returns `any` so tests can cast freely
export type Doc<_TableName extends string> = any
// Generic ID type — a branded string
export type Id<_TableName extends string> = string & { __tableName?: _TableName }
EOF

echo "✅ Stub files generated successfully"
