// Stub file for CI - generated automatically
// This is a minimal stub to satisfy TypeScript during CI when TanStack Router
// codegen hasn't run. The actual routeTree will be generated by the router plugin.

export const routeTree: any = {
  __root__: {} as any,
}
